#!/usr/bin/env bash
# EXP-20-dense — the 4th arm of EXP-20: a PURE DENSE GRPO control on GSM8K.
# Runs the merged vast-ai-workload checkout AS-IS with comm-eff OFF, so it is
# byte-identical to upstream dense verl GRPO. Same training shape as the other
# three EXP-20 arms (mask p=0.95, PowerSGD r=102, r=77) EXCEPT the codec axis is
# collapsed to "dense" (COMM_EFF_ENABLED=false). No code change, no exp bundle.
#
# Generated by experiment-runner and rsync'd to the box; NOT the source of truth
# (the canonical launcher under examples/grpo_trainer/ is). It exists only to pin
# THIS arm's exact 4-env override surface.
set -euo pipefail

cd /workspace/verl

# Belt-and-braces: confirm we are on the merged vast-ai-workload HEAD.
git rev-parse --abbrev-ref HEAD
git log -1 --oneline

# Dense control: the ONLY overrides vs launcher defaults. Everything else
# (batch 128, mini 64, micro 1, dyn_bsz False, n=8, TP=2, mem_util 0.4,
# prompt 1024 / resp 16384, lr 1e-6, no-KL no-entropy, 2 epochs, save 50,
# val_before_train True, ppo_max_token 36864, calc_logprobs True) is the
# launcher default => training-identical to the other three arms.
COMM_EFF_ENABLED=false \
TOTAL_TRAINING_STEPS=50 \
TEST_FREQ=10 \
EXPERIMENT_NAME=ce_dense_50s_gsm8k \
  bash examples/grpo_trainer/vast_comm_eff_baseline_qwen25_1p5b_grpo_gsm8k.sh

echo "$(date -Iseconds) launch_dense.sh wrapper returned"
